# Generated by Django 4.2 on 2024-05-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.PositiveIntegerField(default=0)),
                ('boleta_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='catsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
                ('subcategoria', models.CharField(max_length=250)),
                ('factor_carga', models.IntegerField()),
                ('id_catsub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.operaciones')),
            ],
        ),
    ]
