# Generated by Django 4.2 on 2024-05-20 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catsub',
            name='id_catsub',
        ),
        migrations.AddField(
            model_name='operaciones',
            name='id_catsub',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.catsub'),
            preserve_default=False,
        ),
    ]
