# Generated by Django 4.2 on 2024-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0002_remove_catsub_id_catsub_operaciones_id_catsub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
