# Generated by Django 4.2 on 2024-05-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0003_alter_operaciones_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
