# Generated by Django 4.2 on 2024-05-21 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0004_alter_operaciones_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='id_catsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.catsub'),
        ),
    ]
