# Generated by Django 4.2 on 2024-05-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0005_alter_operaciones_id_catsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='deuda',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=True),
        ),
    ]
