# Generated by Django 4.2 on 2024-05-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0006_operaciones_deuda'),
    ]

    operations = [
        migrations.CreateModel(
            name='id_deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deuda', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='deuda',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False),
        ),
    ]
