# Generated by Django 4.2 on 2024-05-22 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0007_id_deuda_alter_operaciones_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operaciones',
            name='deuda',
        ),
        migrations.AddField(
            model_name='id_deuda',
            name='d_bool',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='id_deuda',
            name='deuda',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='id_catsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.id_deuda'),
        ),
    ]
