# Generated by Django 4.2 on 2024-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0008_remove_operaciones_deuda_id_deuda_d_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_deuda',
            name='deuda',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2),
        ),
    ]
