# Generated by Django 4.2 on 2024-05-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0009_alter_id_deuda_deuda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id_deuda',
            name='d_bool',
        ),
    ]
