# Generated by Django 4.2 on 2024-05-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0010_remove_id_deuda_d_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_deuda',
            name='deuda',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2),
        ),
    ]
