# Generated by Django 4.2 on 2024-05-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0011_alter_id_deuda_deuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='id_deuda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.id_deuda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='id_catsub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.catsub'),
        ),
    ]
