# Generated by Django 4.2 on 2024-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0012_operaciones_id_deuda_alter_operaciones_id_catsub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operaciones',
            old_name='boleta_id',
            new_name='id_boleta',
        ),
    ]
