# Generated by Django 4.2 on 2024-05-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0013_rename_boleta_id_operaciones_id_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='id_catsub',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='id_deuda',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='id_deuda',
        ),
        migrations.AlterField(
            model_name='catsub',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.category'),
        ),
        migrations.AlterField(
            model_name='catsub',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.subcategory'),
        ),
    ]
