# Generated by Django 4.2 on 2024-05-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0014_category_subcategory_alter_operaciones_id_catsub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operaciones',
            name='id_catsub',
        ),
        migrations.AddField(
            model_name='operaciones',
            name='categoria',
            field=models.ManyToManyField(to='TRANSACTION.category'),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='subcategoria',
            field=models.ManyToManyField(to='TRANSACTION.subcategory'),
        ),
        migrations.DeleteModel(
            name='catsub',
        ),
    ]
