# Generated by Django 4.2 on 2024-05-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0015_remove_operaciones_id_catsub_operaciones_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='operaciones',
            name='categoria',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operaciones',
            name='subcategoria',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
