# Generated by Django 4.2 on 2024-05-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0016_subcategory_categoria_remove_operaciones_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.category'),
        ),
    ]
