# Generated by Django 4.2 on 2024-06-06 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0023_remove_category_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='TRANSACTION.category'),
        ),
    ]
