# Generated by Django 4.2 on 2024-06-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0024_alter_subcategory_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operaciones',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='operaciones',
            old_name='subcategoria',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='id_boleta',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='id_deuda',
        ),
        migrations.RemoveField(
            model_name='operaciones',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='multiplicador',
        ),
        migrations.AddField(
            model_name='operaciones',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='TRANSACTION.category'),
            preserve_default=False,
        ),
    ]
