# Generated by Django 4.2 on 2024-06-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0025_rename_categoria_operaciones_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Opt', editable=False, max_length=30),
        ),
    ]
