# Generated by Django 4.2 on 2024-06-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0026_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='name',
            field=models.CharField(default='Opt', max_length=100),
        ),
    ]
