# Generated by Django 4.2 on 2024-06-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0027_alter_operaciones_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
