# Generated by Django 4.2 on 2024-06-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0029_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operaciones',
            name='monto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
