# Generated by Django 4.2 on 2024-07-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0031_alter_operaciones_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='name',
            field=models.CharField(blank=True, default='OPT', max_length=100, null=True),
        ),
    ]
