# Generated by Django 4.2 on 2024-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0032_alter_operaciones_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='multiplicador',
            field=models.IntegerField(choices=[(1, '+'), (-1, '-')], default=1),
        ),
    ]
