# Generated by Django 4.2 on 2024-07-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0033_subcategory_multiplicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_GD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_gd', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fpag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto_Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('daily_purchase', models.CharField(max_length=30)),
                ('fpag', models.CharField(max_length=30)),
                ('monto', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
