# Generated by Django 4.2 on 2024-07-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TRANSACTION', '0034_category_gd_fpag_gasto_diario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fpag',
            name='area',
        ),
    ]
